[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

lib_deps =
  lovyan03/LovyanGFX

monitor_filters = send_on_enter

src_filter = +<*.cpp> +<*.h> -<main\ copy\ 2.cpp>
